import "./globals.css";
import { Inter } from "next/font/google";
import Layout from "./components/layout";
import { AuthProvider } from "./context/AuthContext"; // Add this import

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Layout>{children}</Layout>
        </AuthProvider>
      </body>
    </html>
  );
}
